# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d87cd9ef0910ddd969a3dd6fb0af0076badc27f3e746e2ded953c3ed4be97aeaf1c5c3fe432148318cb357d593033a84eba3d9e4f4843dde00c7bc7e110cb41f

test:
  secret_key_base: c46accce6d99b7a0e9bc2c4255845fc75e69f0b8cd1b4d2eae178b2f81f9b3194dc90372de935fc0d9583e07c30c2fc401355d504714b48755239c1d7c12acaa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
